### ISSUE TITLE
FB update to App creation

### ISSUE THREAD

**Issue by DCFrancis** [spring-guides/gs-accessing-facebook#13]
what do you need to specify for App Domains while you are doing purely local development? (e.g. localhost:8080)

**Comment by dsyer** [comment]
Normally I use localhost:8080. Is that a problem?

**Comment by DCFrancis** [comment]
Facebook update their "My App" settings such that you need to specify which
App Domains, you're application is coming from.

right now I'm just using doing local dev.

**Comment by dsyer** [comment]
I didn't get what the question/problem is yet. You want to know how to set the client id and secret (isn't that in the guide already)?

**Comment by gregturn** [comment]
Perhaps @habuma can check out this issue?

**Comment by DCFrancis** [comment]
I have successfully create an App (so I have the appid and secret)

however, when I first run the app and click to connect to Facebook (You
aren't connected to Facebook yet. Click the button to connect this
application with your Facebook account.)

I get this error from Facebook:

Given URL is not allowed by the Application configuration.: One or more of
> the given URLs is not allowed by the App's settings. It must match the
> Website URL or Canvas URL, or the domain must be a subdomain of one of the
> App's domains.



I believe this is because Facebook has changed the registration process for
apps (note their screens and flow is different from what is described in
http://spring.io/guides/gs/register-facebook-app/)

**Comment by dsyer** [comment]
The screens look different, but the outcome is the same as far as I can tell. What is your site URL in your app settings at https://developers.facebook.com/apps?

**Comment by gregturn** [comment]
@dsyer Actually, I've seen a similar issue when working with Spring Social Ecobee. Over at Ecobee, you have to register a real domain name to get tokens. Once I did that (using my target CF URL), they granted me tokens, and I developed against it with localhost:8080. But this might be an approach to reduce spoofing.

**Comment by dsyer** [comment]
The domain is optional (I don't have it in any of my apps). I updated the "register-facebook" guide accordingly (not this one).
