### ISSUE TITLE
When i click on signIn it throws an error

### ISSUE THREAD

**Issue by hima09** [spring-guides/gs-accessing-facebook#17]
Hii when i click on the "signIn with facebook" button,i got the bellow error.
{
   "error": {
      "message": "Invalid redirect_uri: Given URL is not permitted by the Application configuration",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "GP/UQ51i210"
   }
}
I have added correct appID and app-secret in properties file and m connected to facebook.I couldn't figure out the error.Kindly help

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
