### ISSUE TITLE
Not able to login via facebook

### ISSUE THREAD

**Issue by karthikpamidimarri** [spring-guides/gs-accessing-facebook#18]
I have followed the documentation which has been specified in the readme.md file but not able login the application properly facing the issues as specified in the below link 

http://stackoverflow.com/questions/33122074/spring-boot-social-cannot-connect-to-facebook-via-localhost

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
