### ISSUE TITLE
I am trying to access Facebook using spring.io social but the isAuthorized() method fails

### ISSUE THREAD

**Issue by karthikpamidimarri** [spring-guides/gs-accessing-facebook#19]
I am trying to access Facebook using https://spring.io/guides/gs/accessing-facebook/.

I imported the application in Spring Tool Suite using "Import Spring Getting Started Content". I am able to run the application using "gradlew bootRun" and also using "gradlew build".

The problem I encounter is: It seems that in the HelloController class the test

if (!facebook.isAuthorized()) 
doesn't work. Instead of executing the remaining statements and a return to the "hello" view, the application keeps executing the statement

return "redirect:/connect/facebook"
as if the .isAutorized() method fails.

However, when I open in the same webbrowser www.facebook.com than I get my (logged on) Facebook homepage. The login into Facebook using the application seems to work normally. Please note that I explicitly logout from Facebook before I test the application.

Please note that:

I have registered the application within developer.facebook.com.
I submitted my Facebook AppID and AppSecret into the application.properties file.
I submitted in the Facebook Apps Site URL a hostname.domain using Vitalwerks No-IP. In my router I mapped my public IP address port 80 to the internal IP address of my server port 8080. I am able to access the application using hostname.domain.
What am I doing wrong? The controller class looks like this:

@Controller
@RequestMapping("/")
public class HelloController {

private Facebook facebook;

@Inject
public HelloController(Facebook facebook) {
    this.facebook = facebook;
}

@RequestMapping(method=RequestMethod.GET)
public String helloFacebook(Model model) {
    if (!facebook.isAuthorized()) {
        return "redirect:/connect/facebook";
    }

```
model.addAttribute(facebook.userOperations().getUserProfile());
PagedList<Post> homeFeed = facebook.feedOperations().getHomeFeed();
model.addAttribute("feed", homeFeed);

return "hello";
```

}
}

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
