### ISSUE TITLE
Guide should explain how to allow localhost access to facebook

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-guides/gs-accessing-facebook#20]
After creating your facebook application on Facebook (so you get an app-id and app-secret), you need to do an additional step to allow `localhost` to access Facebook.
1. Select your application under 'My Apps'
2. Go to 'Settings'
3. Select the 'Basic' tab
4. Click on 'Add platform' and select 'Web'
5. Type `http://localhost:8080/` as site URL
6. Add `localhost` under 'App Domains'

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
