### ISSUE TITLE
Guide is using an invalid scope

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-guides/gs-accessing-facebook#21]
Using the current code, you get the following exception from Facebook:

> Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

It seems that `read_stream` has been deprecated. According to http://stackoverflow.com/questions/32309355/get-home-feed-requires-read-stream-which-is-deprecated there is no direct replacement for it anymore.

**Comment by conteit** [comment]
+1

**Comment by gregturn** [comment]
I'll have to ask @habuma to look into this.

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
