### ISSUE TITLE
Missing information about spring.social.auto_connection_views=true 

### ISSUE THREAD

**Issue by mklimasz** [spring-guides/gs-accessing-facebook#22]
I guess it is worth to mention that if we don't use boot starter with thymeleaf we need to setup manually `spring.social.auto_connection_views=true` in application.properties or at least that it happens in background.

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
