### ISSUE TITLE
Missing info about a library

### ISSUE THREAD

**Issue by AndreiD** [spring-guides/gs-accessing-facebook#24]
In the guide, you should add the library 
compile group: 'org.springframework.social', name: 'spring-social-core', version: '2.0.0.M1'

because without it you cannot find the "ConnectionRepository". 

also check the issue about adding localhost as a domain. it's a good tip and if I wouldn't have seen it, I would have probably lost some good minutes trying to debug it.

If you don't have time to add them, I can make a pull request..

**Comment by dsyer** [comment]
The build configurations in this project already use `org.springframework.social:spring-social-facebook` which includes transitively `spring-social-core`, so I don't think it needs to be mentioned explicitly.

Not sure what you mean about localhost. Check what issue? It says in this guide to leave the "domain" field in the app registration empty: https://spring.io/guides/gs/register-facebook-app/. Did you mean that?

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
