### ISSUE TITLE
Issue while connecting to facebook. Too old java?

### ISSUE THREAD

**Issue by Alesanders** [spring-guides/gs-accessing-facebook#25]
I get this error message: 
Sun Jan 29 20:11:30 CET 2017
There was an unexpected error (type=Internal Server Error, status=500).
(#12) bio field is deprecated for versions v2.8 and higher

I have connected my facebook etc correctly. After i login, i get this message. Is the java too old? Can i update this? I do not have mutch programming skills.
I am working on OSX, haven't tried it on windows.

**Comment by dsyer** [comment]
Works for me. Are you running the "complete" sample from this repo?

**Comment by Alesanders** [comment]
yes, using gradelew. osx 10.12, doesn't this error mean that the java of the program is too old? or my own java?

**Comment by dsyer** [comment]
I don't think it means either of those. If I can't reproduce it I don't know what it means though. If looks like an error message from Facebook.

**Comment by Alesanders** [comment]
i got this in my terminal:
2017-02-01 22:04:21.984  WARN 5531 --- [nio-8080-exec-6] o.s.s.connect.web.ConnectController      : Exception while handling OAuth2 callback (The OAuth2 'state' parameter is missing or doesn't match.). Redirecting to facebook connection status page.

**Comment by Alesanders** [comment]
2017-02-01 22:04:08.105 ERROR 5531 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.social.UncategorizedApiException: (#12) bio field is deprecated for versions v2.8 and higher] with root cause

and this

**Comment by AsamiyaSakura** [comment]
Error is thrown from facebook.userOperations().getUserProfile() where the new API from Facebook changes the way of getting user information.

Temporary Work Around (Reference: http://stackoverflow.com/questions/39890885/error-message-is-12-bio-field-is-deprecated-for-versions-v2-8-and-higher)

1. Create a User Class with the fields you required.
(Fields that are able to use:
{ "id", "about", "age_range", "birthday", "context", "cover", "currency", "devices", "education", "email", "favorite_athletes", "favorite_teams", "first_name", "gender", "hometown", "inspirational_people", "installed", "install_type", "is_verified", "languages", "last_name", "link", "locale", "location", "meeting_for", "middle_name", "name", "name_format", "political", "quotes", "payment_pricepoints", "relationship_status", "religion", "security_settings", "significant_other", "sports", "test_group", "timezone", "third_party_id", "updated_time", "verified", "video_upload_limits", "viewer_can_send_gift", "website", "work"})

2. Replace the code similar to follow:
String [] fields = { "id", "email",  "first_name", "last_name" }; //Depends on which field you want.
User userProfile = facebook.fetchObject("me", User.class, fields);

3. Wait for a new fix while using this workaround!

Sorry for my bad English. How you guys understand!

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
