### ISSUE TITLE
(#12) bio field is deprecated for versions v2.8 and higher

### ISSUE THREAD

**Issue by kivimango** [spring-guides/gs-accessing-facebook#27]
When i approve the app's permission request, on the /facebook URL i got a white label error page saying:
(#12) bio field is deprecated for versions v2.8 and higher.

Please update the example's default permissions to not ask bio from fb.Ty.

**Comment by gregturn** [comment]
@habuma got a little time?

**Comment by volkizz** [comment]
Same issue. What is the workaround?

**Comment by kivimango** [comment]
You create a String[] array with the name of the fields you want to retrieve, e.g.:
`String [] fields = { "id", "email",  "first_name", "last_name" };`
then call
`User userProfile = facebook.fetchObject("me", User.class, fields);`
More info on 
https://stackoverflow.com/questions/39890885/error-message-is-12-bio-field-is-deprecated-for-versions-v2-8-and-higher)

**Comment by ninadpchaudhari** [comment]
in addition to @kivimango 's comment, do not forget to add
`import org.springframework.social.facebook.api.User;`

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
